version: "3"
services:
  publish:
    build: .
    ports:
      - 80:5000
  test:
    image: "mcr.microsoft.com/dotnet/sdk:7.0"
    volumes:
      - ./:/app
    expose:
      - 5123
      - 38167
      - 38745
    ports:
      - 5123:5123
      - 38167:38167
      - 38745:38745
    working_dir: /app
    command: dotnet watch run --urls http://0.0.0.0:5123